#' Place a scale bar drawn as a basemap overlay to show the dimensions of the map.
#'
#' @description
#' The size of a map is an important feature that is included on many maps.
#' This function automates the general process of placing a scale bar and
#' an associated text statement with the length and measurement units for
#' the scale bar.
#' 
#' The length of the scale bar is determined automatically. The general width
#' is controlled with a scale width parameter. The actual width of the scale
#' bar is determined by rounding the value of the bar length with a primary
#' greatest value algorithm.
#' 
#' The user can choose whether the dimensions should be metric (m, km) or
#' English (ft, mi).
#' 
#' As with the length of the scale bar, the text for the dimension is rounded 
#' to the primary greatest value. In addition, the scaling shifts from smaller 
#' units (m, ft) to larger units (km, mi) as the length of the bar increases.
#' 
#' A number of other display features are available using param values. These
#' include the text size and color, as well as line thickness and color.
#' 
#' The location of the scale can be chosen from the four alternatives:
#' ll, lr, ul, and ur.
#' 
#' Most of the style values will be defaulted using the param values.
#'
#' @param basemap A basemap generated by ggmap
#' @param styles A data frame of default style values
#'
#' @return An annotated scale bar (line and text)
#' @import tibble ggplot2 geosphere
#' @export
#'

site_scale <- function(basemap, styles = column) {
  
  ## Variable binding
  lon <- lat <- NULL
  
  ## Function magtude #################################
  ## Round a value to the Greatest Place Value
  magtude <- function(x){
    ## Get an appropriate scale line
    y   <- 9    ## Working value (must be 1 or greater)
    mag <- 0    ## Initialize the magnitude
    
    ## Loop to do the rounding to a magnitude (mag is negative)
    while(y > 0){
      x_length <- y
      y <- round(x,mag)
      mag <- mag - 1
    } ## end Loop
    return(x_length)
  } ## end function magtude ##########################
  
  ## Make sure the site_anchor is lowercase
  styles$scale_anchor <- as.character(tolower(styles$scale_anchor))
  
  ## Get the corners of the basemap
  corners <- unlist(attr(basemap, which = "bb"))[c(2, 4, 1, 3)]
  
  left_c   <- corners[[1]]
  right_c  <- corners[[2]]
  bottom_c <- corners[[3]]
  top_c    <- corners[[4]]
  
  ## Get map dimensions
  map_height <- top_c   - bottom_c
  map_width  <- right_c - left_c
  
  x <- (map_width * styles$scale_width) * 111139  ## convert to meters
  
  if(styles$metric == TRUE) {
    
    x_length <- magtude(x)
    
    ## check for km (scale > 1000m to km)
    if(x_length > 1000) {
      scale_value <- x_length/1000
      scale_unit  <- "km"} else {
        scale_value <- x_length
        scale_unit  <- "m"} ## end check for km
    
    ## Put together info for the scale annotation
    scale_text <- paste(scale_value,scale_unit)
    
  } ## end metric section
  
  if(styles$metric == FALSE){
    
    ## convert to feet
    x <- x * 3.28084
    
    x_length <- magtude(x)
    
    ## check for miles (scale < 6000 ft to mi)
    if(x_length < 6000) {
      
      ## Stay with feet
      scale_value <- x_length
      scale_unit  <- "ft"
      x_length <- scale_value * 0.3048} else { ## feet to meters
        
        ## Work with miles
        scale_unit  <- "mi"
        x <- x_length/5280
        
        ## Round miles to the correct magnitude
        x_miles <- magtude(x)
        scale_value <- x_miles
        x_length <- scale_value * 1609.34 ## miles to meters
        
      } ## end feet vs miles section
    
    ## Put together info for the scale annotation
    scale_text <- paste(scale_value,scale_unit)
    
  } ## end English section
  
  ## Get some locations for use below
  left_side   <- left_c   + (map_width  * styles$scale_margin)
  bottom_side <- bottom_c + (map_height * styles$scale_margin)
  right_side  <- right_c  - (map_width  * styles$scale_margin)
  top_side    <- top_c    - (map_height * styles$scale_margin)
  top_text    <- top_c    - (map_height * (styles$scale_margin)/2)
  bottom_text <- bottom_c + (map_height * (styles$scale_margin)/2)
  
  scale_line <- data.frame(lon=NULL,lat=NULL)
  text_loc   <- data.frame(lon=NULL,lat=NULL)
  
  if(styles$scale_anchor == "ll") {
    anchor_left  <- destPoint(c(left_side,bottom_side), 90.0, 0)
    anchor_right <- destPoint(anchor_left,  90.0, x_length)
    scale_line   <- data.frame(rbind(anchor_left,anchor_right))
    text_loc     <- data.frame(destPoint(c(left_side,bottom_text), 90.0, 0))
    justify      <- 0
  }
  
  if(styles$scale_anchor == "lr") {
    anchor_right  <- destPoint(c(right_side,bottom_side), 90.0, 0)
    anchor_left   <- destPoint(anchor_right, 270.0, x_length)
    scale_line    <- data.frame(rbind(anchor_left,anchor_right))
    text_loc      <- data.frame(destPoint(c(right_side,bottom_text), 90.0, 0))
    justify       <- 1
  }
  
  if(styles$scale_anchor == "ul") {
    anchor_left   <- destPoint(c(left_side,top_side), 90.0, 0)
    anchor_right  <- destPoint(anchor_left,  90.0, x_length)
    scale_line    <- data.frame(rbind(anchor_left,anchor_right))
    text_loc      <- data.frame(destPoint(c(left_side,top_text), 90.0, 0))
    justify       <- 0
  }
  
  if(styles$scale_anchor == "ur") {
    anchor_right  <- destPoint(c(right_side,top_side), 90.0, 0)
    anchor_left   <- destPoint(anchor_right, 270.0, x_length)
    scale_line    <- data.frame(rbind(anchor_left,anchor_right))
    text_loc      <- data.frame(destPoint(c(right_side,top_text), 90.0, 0))
    justify       <- 1
  }
  
  ## Put out the map with an annotated scale line
  scale_bar <-
    geom_line(data=scale_line, aes(x=lon, y=lat), 
              size=styles$scale_line_thickness,
              color=styles$scale_line_color) 
    
  scale_words <-
    geom_text(label=scale_text,data=text_loc, aes(x=lon, y=lat), 
              size=styles$scale_text_size, hjust = justify,
              color=styles$scale_text_color)
  
  return (c(scale_bar, scale_words))
  
} ## end site_scale function